version: "3.8"

services:
  # =======================
  # MinIO (S3 backend)
  # =======================
  minio:
    image: minio/minio:latest
    container_name: biopharma-minio
    command: server /data --console-address ":9002"
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    networks:
      - data-platform

  kafka:
    image: apache/kafka:3.7.0
    container_name: biopharma-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@biopharma-kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://biopharma-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - data-platform

  # =======================
  # Iceberg REST Catalog
  # =======================
  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    container_name: biopharma-iceberg-rest
    ports:
      - "8181:8181"
    environment:
      CATALOG_WAREHOUSE: s3://iceberg/warehouse
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_REGION: us-east-1
      S3_ENDPOINT: http://minio:9000
      S3_PATH_STYLE_ACCESS: "true"
    depends_on:
      - minio
    networks:
      - data-platform

  # =======================
  # Spark Master
  # =======================
  spark-master:
    build: ./docker/spark
    container_name: biopharma-spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      ICEBERG_VERSION: 1.9.2
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_REGION: us-east-1
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./config/spark:/opt/spark/conf
      - ./data:/opt/spark/data
    networks:
      - data-platform

  # =======================
  # Spark Worker
  # =======================
  spark-worker:
    build: ./docker/spark
    container_name: biopharma-spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_CORES: 2
      ICEBERG_VERSION: 1.9.2
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_REGION: us-east-1
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./config/spark:/opt/spark/conf
      - ./data:/opt/spark/data
    networks:
      - data-platform

  # =======================
  # Grafana (Visualization)
  # =======================
  grafana:
    image: grafana/grafana:latest
    container_name: biopharma-grafana
    ports:
      - "3000:3000"
    networks:
      - data-platform

volumes:
  minio_data:
  kafka_data:

networks:
  data-platform:
    driver: bridge
